### ISSUE TITLE
String data anonymization

### ISSUE THREAD

**Issue by anishsony** [arx-deidentifier/arx#112]
Hi,

I am reading data from a database table. It contains values in varchar type. I want to anonymize that data. Instead of setting hierarchy manually, i want to set hierarchy dynamically like we do for numbers(we calculate geometric mean or arithmetic mean) . Do we have any utility like that? Please help me out.

**Comment by anishsony** [comment]
Please help me out on this issue?

**Comment by prasser** [comment]
Hi,

thanks for your interest in ARX!

Please take a look at hierarchy generators based on (1) ordering and (2) masking. With both types, you can create hierarchies for strings automatically. Please note, however, that it is likely that you need to manually create hierarchies in order to obtain sufficient data quality.

Best regards
Fabian

**Comment by anishsony** [comment]
Thanks Fabian for helping me out. Do we have any example related to this? I got one example(exmaple18.java). But not quite clear about it.

**Comment by prasser** [comment]
Please also take a look at examples 24 and 25. You can also try the hierarchy builders in the GUI to get a feeling for how they work. Please direct any follow-up questions to arx.deidentifier@gmail.com

I will close this issue now.

Thanks
Fabian

**Comment by anishsony** [comment]
Thank you very much Fabian for help.
