### ISSUE TITLE
IntelliJ: How to run the Examples?

### ISSUE THREAD

**Issue by RunshanHu** [arx-deidentifier/arx#204]
Hi,

I am new to ARX. I git-clone this repository and import it into Intelli IDEA, then I try to run Example 1 in the example folder from the IDE. From the code of Example 1, I supposed it will print something in the CLI due to _printResult(result, data)_ and _System.out.print()_. However, instead of printing anything in the CLI, it opens up a GUI of ARX without any result in it and doesn't display any result in Intelli IDEA. Is this the correct way to run the example? How can I get the result printed out? thank you in advance!

**Comment by marklackey** [comment]
Hi RunshanHu.

I am the author of the Intellij configuration that was recently added to ARX. When I try to run Example1, it seems to work as you expected it to. Here's what I did on my machine (macOS, 10.13.6): 

1. I git cloned arx; then,
2. from Intellij (IDEA 2018.1.6) I selected File->Open, and went to the arx directory and clicked the Open button.
3. Next, I expanded the project tab, expanded the src directory, and navigated to Example1.
4. I right-clicked "Run 'Example1.main()'
5. In the console, I see something like 30 lines of output, starting with "- Time needed: 0.04s"

Maybe it's because you imported instead of just open?  Please try my steps and see if it works for you.

**Comment by prasser** [comment]
Mark, thanks for stepping in!

**Comment by RunshanHu** [comment]
many thanks Mark! your steps work for me!

**Comment by realRuiGuo** [comment]
I've seen this，just Open project， but it has to run Ant build to make it work.
 
![image](https://user-images.githubusercontent.com/12027656/51386189-8c855400-1b5c-11e9-81fc-6653b654cd81.png)
