### ISSUE TITLE
arx-3.7.1.jar has unsigned entries - org/deidentifier/arx/ARXAnonymizer$Result.class[BUG]

### ISSUE THREAD

**Issue by richakhurana19** [arx-deidentifier/arx#284]
Receiving below error during compilation:

.m2/repository/org/deidentifier/arx/arx/3.7.1/arx-3.7.1.jar has unsigned entries - org/deidentifier/arx/ARXAnonymizer$Result.class

**Comment by prasser** [comment]
@nartz Can you help?

**Comment by richakhurana19** [comment]
Can we kindly have the jar in maven central repo?

**Comment by nartz** [comment]
I don't think this is necessarily a bug with ARX code necessarily, and I'm not sure this is something I can actually help with. The jars are not signed because they are just built - maybe this link will help you?

https://stackoverflow.com/questions/17923635/found-unsigned-entry-in-resource

If you are on windows, try running:
`mvn clean package -DskipTests -P win`
or
`mvn clean package -DskipTests -P win-64`

**Comment by richakhurana19** [comment]
@nartz For our product, we just refer to Maven central repo and directly download the jars from there. Individually signing every jar can be an issue, may involve approvals. Also, although I checked out the code but building the jars locally is still an issue. As a general rule, we look up all external dependencies in maven repos for inclusion in pom.xml directly.

**Comment by richakhurana19** [comment]
On the downloads page of arx, can we not just make signed jar available for everyone? And also as a standard process, move the jar to maven central repo? That will be helpful for everyone who uses Arx later.

**Comment by prasser** [comment]
Thanks for your feedback - these are great suggestions, but unfortunately we don't have the time to implement them right now.

Please create issues of type "enhancement" to document the feature requests (there are two: (1) signing the jars, (2) publishing to Maven central). We will then try to implement these enhancements in the future. Closing this issue.
