### ISSUE TITLE
[API] Understanding the RiskModelSampleRisks histogram

### ISSUE THREAD

**Issue by mmailhos** [arx-deidentifier/arx#356]
I would like to understand better how the equivalence class model is calculated as part of the `RiskModelSampleRisks`.

For example, calling `RiskModelSampleRisks.getHighestRisk()` returns the highest re-identification risk of any record in the dataset. It takes the highest value in its own histogram.

I assume X represents the risk with the first element being the equivalence class at the highest risk; and Y represents the frequency.
How is this risk calculated? Is it an average, or some kind of aggregation of the 3 attacks risk? Or is it simply the highest value of all 3? How would that work for the Average Risk?

When calling `RiskModelSampleRisks.getEstimatedProsecutorRisk()`, is it the highest chance of success of a prosecutor attack for a single record? It looks to be always returning 1.0 in my tests.

Thank you very much

**Comment by prasser** [comment]
Thanks for your interest in ARX. The reliable risk measures returned by this class are simply calculated based on the uniqueness of the quasi-identifying attributes in the dataset (e.g. getHighestRisk()), which equals the prosecutor risk.

The estimated risk measures factor in parameters and models that have been used to anonymize a dataset. For example, if k-map has been used to anonymize a dataset, the maximum journalist risk is 1/k. If no estimate can be derived from the configuration, the prosecutor risk is returned as an estimate (because prosecutor > journalist > marketer).

Hope that helps!

**Comment by mmailhos** [comment]
Thank you very much for your response, it really helps.
And a huge thanks also for this project, it's amazing how much it can do.
