### ISSUE TITLE
Bug in hierarchy wizard for dates when using „Quarter of year”

### ISSUE THREAD

**Issue by srcds** [arx-deidentifier/arx#366]
Selecting the “Quarter of year” option when using the hierarchy wizard for dates results in intervals of size 4. The first quarter ranges from ]0, 4] and includes the months 1-3. The second quarter ranges from ]4, 8] and includes the months 4-7, which should not be the case.

![grafik](https://user-images.githubusercontent.com/9593020/143660595-762c54c9-1641-4030-8e0e-18a5b2ea1d54.png)

**Comment by prasser** [comment]
Assigned to @srcds as this is a good oppportunity to better get to know ARX.

**Comment by idhamari** [comment]
**To Reproduce:** 

1. extract the project in this [compressed file sampleData.zip](https://github.com/arx-deidentifier/arx/files/7626200/sampleData.zip). Note: data source is [kaggle](https://www.kaggle.com/shivamb/football-deaths/version/1).
2. Open ARX then File>Open Project> arx/data/iaDatesSample.deid
2. Then Edit>Create hierarchy>use dates (for dates)>Quarter of year

Sample output:

![Screenshot from 2021-11-30 14-54-51](https://user-images.githubusercontent.com/28802516/144060127-86c5b803-13a3-4620-bb68-53be4b600621.png)

The desired output should group the months to be something like:

                 Months     Month indices 
                  1-3             0-2
                  4-6             3-5   
                  7-9             6-8
                  10-12           9-11

**Proposed Solution:**

The code responsible for this behavior can be found [here] (https://github.com/arx-deidentifier/arx/blob/204214fb1a4c56da0fcc85866b69d8bf60452ccd/src/main/org/deidentifier/arx/aggregates/HierarchyBuilderDate.java#L537)                  


            int year = Integer.valueOf(sdf.format(date));
            int lower = (year / _range) * _range;
            int upper = ((year / _range) + 1) * _range;
            return "[" + lower + ", " + upper + "[";

A good solution would be modifying the above equations to produce the correct output. For now, I solved the problem  by introducing a mapping function

	    /**
	     * Map a year to a range  to group months 
	     * @param input
	     * @param granularity
	     * @return
	     */
	    private String year_range_map(String month, int range ) {
	      Map<String , String> month_map = new HashMap < String, String>();
	      int lower = 1; 
	      for (int i=1; i<=12; i++) {
	     	  month_map.put(String.valueOf(i), "[" + String.valueOf(lower) +"-"+   String.valueOf(lower + range -2)   + "]");
	          System.out.println(String.valueOf(i) +"   "+"[" + String.valueOf(lower) +"-"+   String.valueOf(lower + range -2)   + "]");
	    	  if (i%(range-1)==0) {
	    		  lower = lower + range-1;
	    	  };
	      }
	      return month_map.get( String.valueOf(Integer.valueOf(month)) );      }

Then call the above function:

            //int year = Integer.valueOf(sdf.format(date));
            //int lower = (year / _range) * _range;
            //int upper = ((year / _range) + 1) * _range;
            //return "[" + lower + ", " + upper + "[";
            return year_range_map(sdf.format(date), _range);


This is the result:
                   
![Screenshot from 2021-12-06 13-26-00](https://user-images.githubusercontent.com/28802516/144845911-c2b7e690-518c-47c9-826a-7766534b55fc.png)

**Comment by idhamari** [comment]
The code can be found in this [commit](https://github.com/ia-dev/arx/commit/b391961287fb5cffc27fe33a2285aa1034943105)

**Comment by prasser** [comment]
Thanks, a few comments:

(1) For the general process: to work at an issue, please create a branch in your private fork of ARX (forked from unmodified master; never modify the master branch of your private fork). Then create a Pull Request against the ARX repo with this branch, so that we can review the proposed changes here on GitHub.

(2) Regarding your specific fix: I don't think it is correct. You have changed the code to now calculate correct quarters, but the code is generic also used to calculate decades and millenia. So this needs to be fixed differently.

What we see here is actually two bugs:

(a) Quarter is defined as having 4 months. This needs to be fixed in line 191:

QUARTER("MM", 4)   -->    QUARTER("MM", 3),

(b) If you do this, then ARX will show the second bug: For Feburary, e.g., it will generate [0, 3[ which is wrong, but should be [1, 4[ (so +1 must be added to lower and upper).

(c) We can also see that the variable "year" should be named differently (it not only captures years). I would suggest "value" or "timeUnit".

(3) Please try to be as minimally invasive as possible and not change the code's formatting. If you take a look at your link (https://github.com/ia-dev/arx/commit/b391961287fb5cffc27fe33a2285aa1034943105) you will see that intendation is different and you, for example, also changed line 545, where no change is needed.

**Comment by idhamari** [comment]
@prasser thanks for the feedback. The bug is fixed in [this commit](https://github.com/iaBIH/arx/commit/1f7e0036fde12c2d886c86ef0b2c5b6eb08229d3)

**Comment by prasser** [comment]
Code looks good apart from formatting. Please format, create a branch and then a pull request.

**Comment by idhamari** [comment]
An updated and formated version is added [here](https://github.com/arx-deidentifier/arx/pull/371/commits/2653ff11df81f3d7bd1e36a500388cd6c6a216cf) .

**Comment by prasser** [comment]
Fix merge
