### ISSUE TITLE
[BUG] Creating an interval based hierarchy using the Set of values aggregate.

### ISSUE THREAD

**Issue by jenno-verdonck** [arx-deidentifier/arx#380]
**Describe the bug**
Hi,

I was trying to create an interval based hierarchy using the provided builder with the "Set of values" aggregate function. I expected this to create a set representation of all the values contained in the range. ([15-20] becoming {15,16,17,18,19}). The builder however creates a set only containing the bounding values.

**To Reproduce**
1. Create a project containing a numeric quasi-identifier.
2. Create a hierarchy for this value using the hierarchy wizard and select "Use intervals".
3. Build your hierarchy and select the "Set of values" Aggregate function.
4. Click on next and see that the hierarchy doesn't show the set of values but a set of the bounding values.

**Expected behavior**
A "Set of values" aggregate function should display the set of all containing values. The range [15-20] should become {15,16,17,18,19} if the dataset contains all those values. When the dataset does not contain the value 16 the set should become {15,17,18,19}.

**Screenshots**
![image](https://user-images.githubusercontent.com/42772246/160089498-4f8f788b-d04d-425e-8c60-2e75ac797126.png)
![image](https://user-images.githubusercontent.com/42772246/160089546-8a4ab189-730d-48a3-a2b3-503bd68770b3.png)

**ARX GUI:**
 - OS: Windows
 - Version: 3.9.0

**Comment by prasser** [comment]
Thanks, good catch! I think the most interesting question here is why anyone would even want to do that (represent an interval as a set). Maybe the simplest solution is to just remove this option... What do you think?

**Comment by jenno-verdonck** [comment]
Thanks for the fast reply. The set representation could be used as a more controllable version of micro aggregation using sets. It gives more information then the range as it can indicate missing values in the dataset while still following a predefined structure. I can see it having some use-cases but these are quite limited.

**Comment by prasser** [comment]
True. But please note that we are talking about hierarchy creation here. When using ARX's microaggregation method, the set function will work as expected (i.e. include all values)...

**Comment by jenno-verdonck** [comment]
I compared it to micro aggregation because this also allows a set representation. In micro aggregation these are however generated using all values in the equivalence class. While in the hierarchy it would represent all the values in a specific range that are available in the original dataset. I indeed think that this will probably have very limited use-cases and deletion of this function could be considered.

**Comment by prasser** [comment]
Thanks again for reporting this. I've though about it again today. 

Due to the way this is implemented, changing the behaviour of the set aggregate function for the interval-based hierarchy builder would require a lot of work and is probably not worth it.

Actually, all aggregate functions are only applied to the interval limits when used with the interval-based builder. I have added a note to the message on the top of the window stating: "Note: Aggregate functions are only applied to interval limits" to make this transparent to the users.

Final note: although a bit cumbersome, the set representation that you are looking for can be generated by using the order-based hierarchy builder.

Will close this issue now.
