### ISSUE TITLE
Test fails because of missing data files

### ISSUE THREAD

**Issue by sebastianst** [arx-deidentifier/arx#57]
1) After cloning this repo, I tried to run the `test` ant target. It failed because, obviously, the test classes couldn't find the files `../arx-data/data-junit/*.csv`

So I created a folder `arx-data` on the same level as this repo's folder (`arx`) and then created the symbolic link `data-junit -> ../arx/data` to point to the data dir in this repo. Then most tests could run.

Please add this step to the readme file, if it is indeed needed to run the test target.

2) The following `csv` files are still missing in the `data` directory:

- adult_age_microaggregated.csv
- atus.csv
- cup.csv
- cup_hierarchy_RAMNTALL.csv
- dis.csv
- fars.csv
- fars_hierarchy_istatenum.csv
- ihis.csv

Could you add these to the `data` directory?

Thanks!

**Comment by prasser** [comment]
Hi Sebastian,

thank you for your interest in ARX and your feedback!

2) Actually quite a few more files are required to run the tests. Unfortunately we cannot distribute them via the repository for licensing reasons. Please send us an email to arx.deidentifier@gmail.com for information on how to access the required data.

1) Thank you for pointing out these inconsistencies. Due to (2), we internally maintain the datasets and ARX's codebase in different repositories. Maybe it would be a good idea to change this setup, or at least clearly document the steps required to run the tests.

Until this is done, I will leave this issue open.

Thanks
Fabian

**Comment by kohlmayer** [comment]
- Changed all JUnit paths. They now point into the data directory of the workspace,
-  Added readme file with intructions how to obtain the nesessary data to run the JUnit tests
