### ISSUE TITLE
Unable to open a Project

### ISSUE THREAD

**Issue by buddingAnalyst** [arx-deidentifier/arx#69]
Hi,
Whenever I try to open a project which I have already created, I get the following error:

Attribute 'Workclass' : hierarchy misses some values or contains duplicates.

Could you please help me with this?

Thanks,
Udyot

**Comment by prasser** [comment]
Hi Udyot,

thanks for your interest in ARX!

To help you, I need a little more information.

(1) Which version of ARX are you running? The current release? The current development head from git? An older version? Have you created the project file with a different version of ARX? Have you created the project file on a different computer running a different operating system?

(2) If the problem persists, can you send me your project file or does it contain sensitive information?

Best regards
Fabian

**Comment by buddingAnalyst** [comment]
Hi Fabian,

Thank you for replying.
1. I am using the latest version only which I downloaded from ARX website (http://arx.deidentifier.org/downloads/). 

2. Initially I created a project on a sample data and tried to export the hierarchy because I wanted put my own hierarchy so I needed the format. And after saving it was showing me the error: Attribute 'Workclass' : hierarchy misses some values or contains duplicates. But afterwards I didn't click on 'Export Hierarchy' and then I didn't get that error.
I think it is because when I clicked on Export Hierarchy it removed the hierarchy file and hence the error. I hope you can shed some light on this.

3. For my project if I can import my own hierarchy files then that would be awesome. I don't know if I can do that. Maybe you can help me by sharing any hierarchy template?

4. Also I am building a classification algorithm on the anonymized model. Do you think it is possible? I have some questions if we can build predictive models on anonymized datasets, and if you can help me in answering them then that would be very helpful.

Thanks a lot for your time.

Best Regards,
Udyot

**Comment by buddingAnalyst** [comment]
There is one more rrror which I am getting many times whenever I tried to open my already saved project:

"Invalid file format, missing ZIP entry"

I can share my saved file with you, if you need to. I can send it to your email.

Thank you

**Comment by prasser** [comment]
Dear Udyot,

there seem to be some weird things going on with your project file.

1. No, this is not the expected behaviour. When you export a hierarchy, it is not removed from the project. Can you describe a process starting from our initial - unmodified - example.deid project with which I can replicate the problem?

2. Of course you can use your own hierarchy. The easiest way is to create a CSV file which follows the required format (analogously to the way hierarchies are also displayed in the ARX GUI). You can take a look at our example projects to get you started. ARX also provides tools for creating hierarchies, either by simply editing the table in the configuration perspective or by clicking "Edit->Create hierarchy...". Please read our documentation for more details.

3. Of course it is possible to build statistical classifiers that can be trained with anonymized data. In ARX we have included an implementation using logistic regression models. You can compare the performance of classifiers trained with anonymized output data with classifiers trained on the original input data in the following perspective: "Analyze/enhance utility->Classification accuracy". Please not that there is a huge body of literature on how this can be implemented and many papers include experiments with statistical classifiers to evaluate the utility of output data. I would recommend studying the literature first. The following paper may provide a good starting point:

Inan A, Kantarcioglu M, Bertino E. Using anonymized data for classification. In2009 IEEE 25th International Conference on Data Engineering 2009 Mar 29 (pp. 429-440). IEEE.

4. The error message "Invalid file format, missing ZIP entry" indicates that your project-file may have been corrupted. In order to help me debug your issue, please provide me with the following information:

(a) Have you used the project file on different computers? E.g. saved it on computer A and opened it on computer B?

(b) Which operating system are you using? Mac, Windows or Linux?

(c) Please send me the project files in question, with a quick description of the error you receive for each of the files. You should know my email address from our other correspondence.

Best regards
Fabian

**Comment by prasser** [comment]
Dear Udyot,

thank you very much for your bug reports! We have just fixed two bugs:

(1) "Attribute 'Workclass' : hierarchy misses some values or contains duplicates". The trigger for this bug was that your Excel dataset contains values starting with whitespaces. For example, instead of "Widowed" your file contained " Widowed" (You may want to fix this). ARX handled these cases inconsistently when different types of data import were used (e.g. data imported from Excel but hierarchies imported from CSV or created with ARX). Sometimes, values were trimmed when loading or saving data, sometimes not. This is now fixed in a backwards compatible manner, so you should be able to use your existing project files 

(2) "Invalid file format, missing ZIP entry". This bug was triggered by creating projects which contained quasi-identifiers for which no hierarchy was defined. This is now also fixed in a backwards compatible manner, so you should be able to use your existing project files.

Thanks again for taking the time to report these issues. I will close this bug report now. If you encounter further issues or think that your bug has not been fixed, please open a new issue on GitHub.

Best regards
Fabian

P.S.: I recommend to use our current development version of ARX (master branch) until we are able to provide a bugfix release. As a thank you for your efforts, I will soon send you a link to an installer for a preliminary version of upcoming ARX 3.4.2.
