### ISSUE TITLE
Error 15 in import CSV data interface

### ISSUE THREAD

**Issue by lynn-koo** [arx-deidentifier/arx#74]
Hi there,

I am currently using version 3.4.2. 
The ARX tools is showing me an error with number 15 at the interface of importing CSV data.
The output of dataset is not displayed in the GUI and anonymized dataset is not analysed in the tool.
Is there any solution is resolve import CSV file issue ?

Thank you.

**Comment by prasser** [comment]
Dear lynn-koo,

Thanks for your interest in ARX and thanks for reporting this issue. Can you provide us with a CSV file which can be used to reproduce the error?

Best regards
Fabian

**Comment by lynn-koo** [comment]
Hi Fabian,

Here is the CSV file.

[adultdata.zip](https://github.com/arx-deidentifier/arx/files/511295/adultdata.zip)

**Comment by prasser** [comment]
Dear lynn-koo,

your CSV-file contains a syntax error. The header ends with a "," and it thus specifies 16 fields, while each record consists of only 15 fields.

I have modified the parser, so that it will fail with a more specific error message in upcoming releases of ARX.

Thanks for reporting this issue!
Fabian
